#Properties for lokal kjøring mot kafka-cluster i test-scope
spring.kafka.consumer.group-id=testingtesting123_hei

spring.kafka.bootstrap-servers=d26apvl00159.test.local:8443,d26apvl00160.test.local:8443,d26apvl00161.test.local:8443
spring.kafka.properties.schema.registry.url=https://kafka-test-schema-registry.nais.preprod.local

journalfoeringHendelse-v1.topic=aapen-dok-journalfoering-v1-t6
journalpostEndret.topic=privat-dok-journalpostEndret-v1-t6
