###############################################
#                  SPRING BOOT                #
###############################################
application.name=joarkinngaaendehendelser
application.version=@version@
spring.profiles.active=remote
spring.main.banner-mode=off
logging.config=classpath:logback-nais.xml
###############################################
#                    KAFKA                    #
###############################################
spring.kafka.properties.ssl.truststore.location=${javax.net.ssl.trustStore}
spring.kafka.properties.ssl.truststore.***passord=gammelt_passord***}
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${serviceuser.username}" ***passord=gammelt_passord***}";

spring.kafka.client-id=${application.name}
journalpostEndret.topic=privat-dok-journalpostEndret-v1-t6

spring.kafka.consumer.max-poll-records=1
spring.kafka.consumer.poll-timeout=1000
spring.kafka.consumer.enable.auto.commit=false
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.group-id=${application.name}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaJsonDeserializer

inngaaendeJournalpostEndret.topic=aapen-dok-inngaaendeJournalpostEndret-v1-t6

spring.kafka.producer.acks=all
spring.kafka.producer.retries=5
spring.kafka.producer.properties.max.block.ms=2000
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.transaction-id-prefix=${application.name}
spring.kafka.producer.properties.max.in.flight.requests.per.connection=1
spring.kafka.producer.key-serializer=io.confluent.kafka.serializers.KafkaJsonSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaJsonSerializer
