kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: joarkjournalfoeringhendelser
  namespace: default
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: SECURITYTOKENSERVICE_URL
      value: {{ SECURITYTOKENSERVICE_URL }}
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: {{ SPRING_KAFKA_BOOTSTRAP_SERVERS }}
    - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
      value: {{ SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL }}
    - name: JOURNALFOERINGHENDELSE_V1_TOPIC
      value: {{ JOURNALFOERINGHENDELSE_V1_TOPIC }}
    - name: JOURNALPOSTENDRET_TOPIC
      value: {{ JOURNALPOSTENDRET_TOPIC }}
  image: {{ image }}
  ingresses:
    - {{ INGRESSES }}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
    timeout: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVJOARKJOURNALFOERINGHENDELSER }}
        mountPath: /var/run/secrets/nais.io/srvjoarkjournalfoeringhendelser
