kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APPNAVN }}
  namespace: {{ NAMESPACE }}
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: APPNAVN
      value: {{ APPNAVN }}
    - name: JOURNALFOERINGHENDELSE_TOPIC
      value: {{ JOURNALFOERINGHENDELSE_TOPIC }}
    - name: JOURNALPOSTENDRET_TOPIC
      value: {{ JOURNALPOSTENDRET_TOPIC }}
  image: {{ image }}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
    timeout: 10
  port: 8080  
  prometheus:
    enabled: true
    path: /actuator/prometheus
  kafka:
    pool: {{ KAFKA_POOL }}
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
