kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APPNAVN }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
        - {{ this }}
      {{/each}}
  env:
    - name: JAVA_TRUSTSTORE_OPTIONS
      value: "-Djavax.net.ssl.trustStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.trustStorePassword=$(NAV_TRUSTSTORE_PASSWORD)"
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=75
              $(JAVA_TRUSTSTORE_OPTIONS)"
    - name: APPNAVN
      value: {{ APPNAVN }}
    - name: JOURNALFOERINGHENDELSE_TOPIC
      value: {{ JOURNALFOERINGHENDELSE_TOPIC }}
    - name: JOURNALPOSTENDRET_TOPIC
      value: {{ JOURNALPOSTENDRET_TOPIC }}
  liveness:
    path: /actuator/health/liveness
    initialDelay: 20
  readiness:
    path: /actuator/health/readiness
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  kafka:
    pool: {{ KAFKA_POOL }}
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 20m
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki