name: Dependabot
on:
  push:
    branches:
      - 'dependabot/**'

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: read
      packages: write
    uses: navikt/dok-workflows/.github/workflows/build-app.yml@main
    secrets: inherit