name: Dependabot
on:
  pull_request:
    branches: [ master ]

# Set the access for individual scopes, or use permissions: write-all
permissions:
  contents: read
  packages: write

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: navikt/dok-workflows/.github/workflows/build-deploy-feature.yml@main
    secrets: inherit