name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    uses: navikt/dok-workflows/.github/workflows/build-and-publish.yaml@main
    with:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
    secrets: inherit

  deploy-dev:
    uses: navikt/dok-workflows/.github/workflows/deploy-dev.yaml@main
    needs: build-and-publish
    strategy:
      matrix:
        environment: [q1, q2]
    with:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
      NAIS_VARIABLES: nais/${{ matrix.environment }}-config.json
    secrets: inherit

  update_release_draft:
    uses: navikt/dok-workflows/.github/workflows/release-drafter.yml@main
    needs: deploy-dev
    secrets: inherit
